### ISSUE TITLE
How to understand the data in Table 3 of the article?

### ISSUE THREAD

**Issue by wpumain** [gmberton/deep-visual-geo-localization-benchmark#10]
In section 4.1, you mentioned the following:Moreover, results considerably depend on the training data: as an example, training the same network on Pitts30k or MSLS yields a 30% gap testing the model on St. Lucia, as well as a noticeable difference on other datasets too. This effect demonstrates that comparing models trained on different datasets, as done in [85], can be misleading.

In the fourth row of data in Table 3, the model was trained in MSLS and then tested in MSLS, which was far worse than that tested in St Lucia. How to understand this? Generally speaking, the model is trained on data set A, so the test effect on data set A should be better than that on other data sets.

**Comment by gmberton** [comment]
All considered datasets are very different, results on St Lucia are higher because it is a simpler dataset, much smaller in size than MSLS.

**Comment by wpumain** [comment]
Think you for your help
