### ISSUE TITLE
how to reproduce the result about VIT-Netvlad

### ISSUE THREAD

**Issue by Kaacoinnn** [gmberton/deep-visual-geo-localization-benchmark#12]
hi, thanks for your great work about the VPR bench! 
But  when I try to reproduce the VIT-netvlad, I don't know how to do, Could you show me the process that to reproduce the result.  
Another question is that, I check the VIT model in the network.py, but can not find the structure of VIT, about its block number or some other information. So can I change another VIT model in your code structure?

**Comment by gmberton** [comment]
Hello, thank you for your interest!
To reproduce the results with ViT you should train with the following hyperparameters
`--trunc_te=10 --freeze_te=None --resize=384 384`

**Comment by Kaacoinnn** [comment]
thanks for replying, as I set --freeze_te=None, an error came up: 
  train.py: error: argument --freeze_te: invalid choice: 'None' (choose from -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13)
how to solve this error?^_^

**Comment by Kaacoinnn** [comment]
thanks for replying! I set the hyperparameters as you mentioned, but as I run the order: python train.py --dataset_name=msls --backbone=vit --aggregation=netvlad --mining=partial --trunc_te=10 --freeze_te=-1
It raised an error, that is : **AttributeError: 'BaseModelOutputWithPooling' object has no attribute 'norm'**
this error can be traced in  outputs = backbone(inputs)  &&  norm_outputs = F.normalize(outputs, p=2, dim=1) in **model/aggregation.py** T_T
I don't know how this error raised, can you show me how to solve this problem???

**Comment by ga1i13o** [comment]
Hello, I run one more test just to  make sure but for me the following command is working fine:
`python train.py --dataset_name=msls --backbone=vit --aggregation=netvlad --mining=partial --trunc_te=10 --freeze_te=-1  --resize 224 224`

Did you pull the last version of the code?

**Comment by Kaacoinnn** [comment]
hello, very appreciate for replying my question! my code version is actually earlier one, followed your advice, I download the last code, and reuse the command, the code is working fine for me too. Really thanks!!!!!! ^ _ ^

**Comment by Kaacoinnn** [comment]
HI，there. I noticed that the VIT model in vg_bench is achieved by 

> from transformers import ViTModel

**Comment by Kaacoinnn** [comment]
HI，there. I noticed that the VIT model in vg_bench is achieved by` from transformers import ViTModel` , but I cannot find the actual model of VIT, it seems like the VITmodel is compact and unchangeable one. So if I wanna to change the vitmodel or add some other structure in VIT, what can I do for more experiment? would you like show me the process? ^_^

**Comment by gmberton** [comment]
The ViTModel is used as a backbone. You can change the number of layers in the model from command line (with the param `--trunc_te`) and the number of layers that are frozen (with the param `--freeze_te`).
We designed the code so that a model is made of a backbone and an aggregation: so when using ViT as a backbone you can use a number of aggregations, like NetVLAD, CLS and GeM. You can modify the backbone or the aggregation as you wish in these functions [`get_aggregation()`](https://github.com/gmberton/deep-visual-geo-localization-benchmark/blob/main/model/network.py#L59) and [`get_backbone()`](https://github.com/gmberton/deep-visual-geo-localization-benchmark/blob/main/model/network.py#L106)

**Comment by Kaacoinnn** [comment]
thanks for replying，so I can't change the VIT structure? for example, if I wanna pay my effort on **adjusting or adding some new modules in VIT** as backbone and make it performs better under the training process. Not just change the number of layers, can I achieve this?

**Comment by gmberton** [comment]
The aggregation is equivalent to having some layers at the end. If you want to modify the middle of the architecture, you need to add the code for your own backbone, perhaps the same as ViT, and then modify that.
Note that this would be the case for other backbones as well, like ResNets, where it is not straightforward to modify a layer in the middle.
