### ISSUE TITLE
ERROR raised as downloading the pretrained model

### ISSUE THREAD

**Issue by Kaacoinnn** [gmberton/deep-visual-geo-localization-benchmark#13]
Hi, as I reproduce the result of cct+netvlad, I used the command:  `python train.py --dataset_name=msls --backbone=cct384 --aggregation=netvlad --mining=partial --trunc_te=8 --freeze_te=1  --resize 384 384 --negs_num_per_query=5`, and then an error raised `urllib.error.HTTPError: HTTP Error 404: Condition Intercepted` it seems like I cannot log into the web of pretrained model. Then I directly log into the website, it shows

>  thank you for your request. Unfortunately, the page you requested /~alih/compact transformers/checkpoints/finetuned/cct_14_7x2_384_imagenet.pth does not exist.

**Comment by ga1i13o** [comment]
Hello, the problem is that the authors changed the hosting service for the pre-trained models.
I have now updated the links to the models, so it should work fine

**Comment by Kaacoinnn** [comment]
really appreciate it！
