### ISSUE TITLE
A problem for training

### ISSUE THREAD

**Issue by neil45853584** [gmberton/deep-visual-geo-localization-benchmark#14]
Hello! The following problems occurred during my training. No response for a long time, about a few hours. What caused this?

![0853225678650485b48c2e505b3eb43](https://user-images.githubusercontent.com/70128233/228462866-a9d2b23a-030b-477b-ada8-76df2b38cecd.png)

**Comment by neil45853584** [comment]
Generally speaking, how many gigabytes of graphic memory can meet training requirements?

**Comment by ga1i13o** [comment]
GPU memory requirements can wildly vary based on the parameters that you specify. To reduce the memory footprint, you can:
- use a lighter backbone ( in the picture you are using a ResNet-50; you can use a much lighter ResNet-18)
- reduce image resolution ; e.g. we show that using  80%  of original resolution ( = 384,512 ) you don't lose performances
- reduce batch size from 4  to 2

With these little tweaks you can fit into as little as 2-3 GBs of memory

**Comment by neil45853584** [comment]
> Thank you! @ga1i13o 
I tried as you said, and it does work properly now.
