### ISSUE TITLE
Some questions about VITWrapper in network.py

### ISSUE THREAD

**Issue by Kaacoinnn** [gmberton/deep-visual-geo-localization-benchmark#15]
Hi there, I noticed the VitWrapper in network.py. Would you please show me the meaning of VitWrapper? why the vit backbone should pop the class token `self.vit_model(x).last_hidden_state[:, 1:, :]` when connect with netvlad or gem aggregation layer? ^ ^

**Comment by ga1i13o** [comment]
Hello,
it was simply an implementation choice that we had to make since we were the first to apply transformers for geolocalization. The results in our paper are obtained with that configuration.
The choice stems from the fact that ViT is trained to encorporate global information in the CLS token, whereas NetVLAD and GeM are designed to operate on local features from CNNs, thus without global features.
However if you want to can try keeping the CLS even with those aggregations

**Comment by Kaacoinnn** [comment]
thx for replying!! I'll try to keep the CLS with Netvlad~~  

the confuse thing is that if the dimension of the output from VIT cannot match the input dimension of NetVlad.

**Comment by ga1i13o** [comment]
in the same way as netvlad with cnn can accept any size of feature maps, it can accept any number of tokens with transformers. it only depends on the dimension of the token
thus you should not have any problems

**Comment by Kaacoinnn** [comment]
sorry for another question, I am confused about the arg.work_with_tokens in  aggregation.py (126 lines). It shows that:
```
def forward(self, x):
        if self.work_with_tokens:
            x = x.permute(0, 2, 1)
            N, D, _ = x.shape[:]
        else:
            N, D, H, W = x.shape[:]
```

I think this argument is used to distinguish the type of output from backbone. However, I don't find it in parser.py. 

When I use your vitmodel as backbone, I found that the self.work_with_tokens is TRUE, but when I change my own vit model as backbone, then the error raised:
```
    N, D, H, W = x.shape[:]
ValueError: not enough values to unpack (expected 4, got 3)

```
it seemed that the work_with_tokens is not used, so my question is that where this argument is and how to assign it？

**Comment by Kaacoinnn** [comment]
Hi，I am trying to change the VIT model instead of using `from transformers import ViTModel`. However, I used the `vit_base_patch16_384`  MODEL which is the same as your configuration -- `backbone = ViTModel.from_pretrained('google/vit-base-patch16-384')`, but I get a really poor result as ` Recalls on val set < BaseDataset, msls - #database: 18871; #queries: 11084 >: R@1: 2.4, R@5: 4.7, R@10: 6.3, R@20: 8.8` T T. 
      As a comparison, the results obtained by running your program for the same  epoch are: `Rcalls on val set < BaseDataset, msls - #database: 18871; #queries: 11084 >: R@1: 72.6, R@5: 84.8, R@10: 88.3, R@20: 91.1` 
So, I don't know why this poor result raised, I just replaced the backbone from your  ‘from transformers import ViTModel‘ to a certain structure with the same configuration. 
So, Could you please add an certain Vit model in your code instead of using `from transformers import ViTModel`?
