### ISSUE TITLE
Pretrained Model Links are not valid

### ISSUE THREAD

**Issue by iceiceyaphets** [gmberton/deep-visual-geo-localization-benchmark#16]
Hi,

The models links are no longer valid now.
# Pretrained models on Google Landmarks v2 and Places 365
PRETRAINED_MODELS = {
    'resnet18_places'  : '1DnEQXhmPxtBUrRc81nAvT8z17bk-GBj5',
    'resnet50_places'  : '1zsY4mN4jJ-AsmV3h4hjbT72CBfJsgSGC',
    'resnet101_places' : '1E1ibXQcg7qkmmmyYgmwMTh7Xf1cDNQXa',
    'vgg16_places'     : '1UWl1uz6rZ6Nqmp1K5z3GHAIZJmDh4bDu',
    'resnet18_gldv2'   : '1wkUeUXFXuPHuEvGTXVpuP5BMB-JJ1xke',
    'resnet50_gldv2'   : '1UDUv6mszlXNC1lv6McLdeBNMq9-kaA70',
    'resnet101_gldv2'  : '1apiRxMJpDlV0XmKlC5Na_Drg2jtGL-uE',
    'vgg16_gldv2'      : '10Ov9JdO7gbyz6mB5x0v_VSAUMj91Ta4o'
}

**Comment by ga1i13o** [comment]
hello, thanks for pointing it out, I will fix broken links soon

**Comment by iceiceyaphets** [comment]
thanks for the response.

**Comment by gmberton** [comment]
Hello @iceiceyaphets , sorry for the delay. You can now find those models at this link 
https://www.dropbox.com/sh/qe3kc2ic187huh9/AACSLRkvnrx8wgmDxZCdThyka?dl=0
