### ISSUE TITLE
Use of CCT-NetVLAD

### ISSUE THREAD

**Issue by Steven-jiaqi** [gmberton/deep-visual-geo-localization-benchmark#19]
Hello, I really appreciate for your great work. I'm having some trouble with the model you provided. For example, I want to use the model you provided (CCT-NetVLAD) to extract a 1D vector of an image. How should I proceed? 
I'm sorry to bother you.
Best wishes!
Thank you in advance.

**Comment by ga1i13o** [comment]
Hi
You can use the model by simply instatiating it with the right args (eval.py L60 https://github.com/gmberton/deep-visual-geo-localization-benchmark/blob/4d07a3c5598a04c7a97e70542aad3b9301b769e8/eval.py#L60) and loading the weights we released (eval.py L89 https://github.com/gmberton/deep-visual-geo-localization-benchmark/blob/4d07a3c5598a04c7a97e70542aad3b9301b769e8/eval.py#L89) 

You can then forward the images and get your descriptors. You can use the code in the BaseDataset class __get_item__ to load the images

**Comment by Steven-jiaqi** [comment]
Thanks for your reply. When i run "python3 eval.py --backbone=cct384 --aggregation=netvlad  --resume=logs/msls_cct384tr8fz1_netvlad.pth' ,the error happen:
Traceback (most recent call last):
  File "eval.py", line 90, in <module>
    model = util.resume_model(args, model)
  File "/home/user/yjq/deep-visual-geo-localization-benchmark-main/util.py", line 42, in resume_model
    model.load_state_dict(state_dict)
  File "/home/user/.conda/envs/seqnet2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1223, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for GeoLocalizationNet:
        Missing key(s) in state_dict: "backbone.classifier.blocks.8.pre_norm.weight", "backbone.classifier.blocks.8.pre_norm.bias", "backbone.classifier.blocks.8.self_attn.qkv.weight", "backbone.classifier.blocks.8.self_attn.proj.weight", "backbone.classifier.blocks.8.self_attn.proj.bias", "backbone.classifier.blocks.8.linear1.weight", "backbone.classifier.blocks.8.linear1.bias", "backbone.classifier.blocks.8.norm1.weight", "backbone.classifier.blocks.8.norm1.bias", "backbone.classifier.blocks.8.linear2.weight", "backbone.classifier.blocks.8.linear2.bias", "backbone.classifier.blocks.9.pre_norm.weight", "backbone.classifier.blocks.9.pre_norm.bias", "backbone.classifier.blocks.9.self_attn.qkv.weight", "backbone.classifier.blocks.9.self_attn.proj.weight", "backbone.classifier.blocks.9.self_attn.proj.bias", "backbone.classifier.blocks.9.linear1.weight", "backbone.classifier.blocks.9.linear1.bias", "backbone.classifier.blocks.9.norm1.weight", "backbone.classifier.blocks.9.norm1.bias", "backbone.classifier.blocks.9.linear2.weight", "backbone.classifier.blocks.9.linear2.bias", "backbone.classifier.blocks.10.pre_norm.weight", "backbone.classifier.blocks.10.pre_norm.bias", "backbone.classifier.blocks.10.self_attn.qkv.weight", "backbone.classifier.blocks.10.self_attn.proj.weight", "backbone.classifier.blocks.10.self_attn.proj.bias", "backbone.classifier.blocks.10.linear1.weight", "backbone.classifier.blocks.10.linear1.bias", "backbone.classifier.blocks.10.norm1.weight", "backbone.classifier.blocks.10.norm1.bias", "backbone.classifier.blocks.10.linear2.weight", "backbone.classifier.blocks.10.linear2.bias", "backbone.classifier.blocks.11.pre_norm.weight", "backbone.classifier.blocks.11.pre_norm.bias", "backbone.classifier.blocks.11.self_attn.qkv.weight", "backbone.classifier.blocks.11.self_attn.proj.weight", "backbone.classifier.blocks.11.self_attn.proj.bias", "backbone.classifier.blocks.11.linear1.weight", "backbone.classifier.blocks.11.linear1.bias", "backbone.classifier.blocks.11.norm1.weight", "backbone.classifier.blocks.11.norm1.bias", "backbone.classifier.blocks.11.linear2.weight", "backbone.classifier.blocks.11.linear2.bias", "backbone.classifier.blocks.12.pre_norm.weight", "backbone.classifier.blocks.12.pre_norm.bias", "backbone.classifier.blocks.12.self_attn.qkv.weight", "backbone.classifier.blocks.12.self_attn.proj.weight", "backbone.classifier.blocks.12.self_attn.proj.bias", "backbone.classifier.blocks.12.linear1.weight", "backbone.classifier.blocks.12.linear1.bias", "backbone.classifier.blocks.12.norm1.weight", "backbone.classifier.blocks.12.norm1.bias", "backbone.classifier.blocks.12.linear2.weight", "backbone.classifier.blocks.12.linear2.bias", "backbone.classifier.blocks.13.pre_norm.weight", "backbone.classifier.blocks.13.pre_norm.bias", "backbone.classifier.blocks.13.self_attn.qkv.weight", "backbone.classifier.blocks.13.self_attn.proj.weight", "backbone.classifier.blocks.13.self_attn.proj.bias", "backbone.classifier.blocks.13.linear1.weight", "backbone.classifier.blocks.13.linear1.bias", "backbone.classifier.blocks.13.norm1.weight", "backbone.classifier.blocks.13.norm1.bias", "backbone.classifier.blocks.13.linear2.weight", "backbone.classifier.blocks.13.linear2.bias". 

The model is from the model zoo.This mistake confuses me.Do you know how to fix this?
I'm sorry to bother you.
Best wishes!
Thank you in advance.

**Comment by ga1i13o** [comment]
You are right, we should have made this more clear. The model, as you can read in the filename, is truncated at layer 8 and frozen at layer 1.
So you have to specify `--trunc_te 8 --freeze_te 1`

**Comment by Steven-jiaqi** [comment]
Thanks a lot for your help!
