### ISSUE TITLE
reproduce the result of CCT-NetVLAD

### ISSUE THREAD

**Issue by Lu-Feng** [gmberton/deep-visual-geo-localization-benchmark#2]
Hi, I really appreciate for the work you've done. I wonder if the CCT-NetVLAD model will be released. How should I set parameters (trunc_te/freeze_te) to reproduce the result of CCT-NetVLAD on MSLS dataset.

**Comment by rm-wu** [comment]
Hi @Lu-Feng,
Thanks for your interest in our work! To reproduce the results with CCT+NetVLAD on MSLS, you must set `--trunc_te=8 --freeze_te 1`.
We will update the trained model soon! Thanks for pointing out that it is missing!

**Comment by Lu-Feng** [comment]
> Hi @Lu-Feng, Thanks for your interest in our work! To reproduce the results with CCT+NetVLAD on MSLS, you must set `--trunc_te=8 --freeze_te 1`. We will update the trained model soon! Thanks for pointing out that it is missing!

Thanks for your reply! I have reproduced the result with your help.

**Comment by ga1i13o** [comment]
Hello, I uploaded the pre-trained models, with a link in the README. An additional note about the results with CCT, you can notice an improvement specifying a "--negs_num_per_query" lower than 10, like 2 or 5
