### ISSUE TITLE
ViT model

### ISSUE THREAD

**Issue by LKELN** [gmberton/deep-visual-geo-localization-benchmark#21]
Thanks for your great work!Can you provide a download  of your ViT model and the training configurations?

**Comment by ga1i13o** [comment]
Hi, I have added to the Readme a link to a ViT model, trained with 224x224 resolution. Results in the paper were obtained using 384x384, for fairer comparison with CNNS that used 640x480. You can train a model to reproduce results in the paper with the following command:

`python3 train.py --dataset_name=msls --backbone=vit --aggregation=cls --trunc_te 10 --resize 384 384`

If you like you can also change the aggregation to 'gem' or `netvlad`

**Comment by LKELN** [comment]
Thanks! What is your suggestion if I want to use VIT huge or VIT large,--trunc_te parameters? How many GPUs did you use to train the VIT base model, and how big was the train_batchsize? Have you tried the full training VIT base?

**Comment by ga1i13o** [comment]
Hi, in my experiments truncating at 10 (as in the example above) gives a slight boots ( +1.5 points), and truncating more is counterproductive. Also freezing gave slightly worse results, but you can truncate up to layer 3 if you want to speed up experiments.
I used batch size of 4; if it does not fit in memory you can reduce the number of negatives in the triplet to 5, it does not affect results. I don't remember how many gpus I used but for sure not more than 2. You can also cut batch size to 2, and results should not change much
