### ISSUE TITLE
Error on train.py

### ISSUE THREAD

**Issue by GyoungTaeChae** [gmberton/deep-visual-geo-localization-benchmark#28]
Hello.

i encountered below error at start of the train.py

```
2024-08-06 04:59:17   The outputs are being saved in logs/default/2024-08-06_04-59-17
2024-08-06 04:59:17   Using 4 GPUs and 60 CPUs
2024-08-06 04:59:17   Loading dataset pitts30k from folder ../geo_localization/datasets/
2024-08-06 04:59:17   There are 96 queries without any positives within the training set. They won't be considered as they're useless for training.
2024-08-06 04:59:17   
Traceback (most recent call last):
  File "train.py", line 37, in <module>
    triplets_ds = datasets_ws.TripletsDataset(args, args.datasets_folder, args.dataset_name, "train", args.negs_num_per_query)
  File "/home/work/deep-visual-geo-localization-benchmark/datasets_ws.py", line 190, in __init__
    self.hard_positives_per_query = np.delete(self.hard_positives_per_query, queries_without_any_hard_positive)
  File "<__array_function__ internals>", line 200, in delete
  File "/home/work/anaconda3/envs/8/lib/python3.8/site-packages/numpy/lib/function_base.py", line 5126, in delete
    arr = asarray(arr)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (7416,) + inhomogeneous part.
```

i type only python train.py so, dataset was pitts30k.   
i don't think it's problem of code. because many people use this repo very well

```

# Remove queries without positives
        self.hard_positives_per_query = np.delete(self.hard_positives_per_query, queries_without_any_hard_positive)
        self.soft_positives_per_query = np.delete(self.soft_positives_per_query, queries_without_any_hard_positive)
        self.queries_paths = np.delete(self.queries_paths, queries_without_any_hard_positive)
```
 the error points this.(dataset_ws.py) can you advise how to fix this error?

**Comment by GyoungTaeChae** [comment]
Upon debugging, I found that queries_without_any_hard_positive is of type numpy.ndarray 
while self.hard_positives_per_query is of type list. 
This type mismatch caused the error when calling np.delete.

To resolve this, I replaced the np.delete call with list comprehensions to remove the elements corresponding to the indices in queries_without_any_hard_positive. 


```
self.hard_positives_per_query = [p for i, p in enumerate(self.hard_positives_per_query) if i not in queries_without_any_hard_positive]
self.soft_positives_per_query = [p for i, p in enumerate(self.soft_positives_per_query) if i not in queries_without_any_hard_positive]
self.queries_paths = [p for i, p in enumerate(self.queries_paths) if i not in queries_without_any_hard_positive]
This change successfully resolved the issue, and the script is now running without errors.
```
However, since this modification alters the original logic, I wanted to confirm if this is the correct and intended approach to handle this issue.

**Comment by ga1i13o** [comment]
this is due to a change in numpy (after 1.21.something)  which raises this error that was previously only given with a UserWarning
did you install the env as specified in the requirements.txt file ?
if you wish to stick to a more recent numpy, it should be solved by casting the list to array of objects, like this  `queries_without_any_hard_positive = np.asarray(queries_without_any_hard_positive, dtype='object')
alternatively, your proposed fix is also fine, just a bit slower

**Comment by GyoungTaeChae** [comment]
thank you very much god
i'll close this issue :)
