### ISSUE TITLE
Visualize the predictions

### ISSUE THREAD

**Issue by MAX-OTW** [gmberton/deep-visual-geo-localization-benchmark#4]
Hello, @gmberton @ga1i13o ,I really appreciate for your great work. Now I want to obtain a list of the top N images retrieved for each query in the test dataset in the test stage.It  just need to output a txt file( including the prediction results ),so as to verify the retrieval ability of the algorithms mentioned in the paper. 
Is it possible to add a piece of code on the basis of this benchmark to achieve this？What should I do? Could you give me some suggestions?
I am always looking forward to your kind response.
Best regards.

**Comment by gmberton** [comment]
Hi @MAX-OTW , thanks for your interest!
To visualize the images you can add at
https://github.com/gmberton/deep-visual-geo-localization-benchmark/blob/main/test.py#L222
this line of code which saves the predictions to a file
```    np.save("predictions.npy", predictions)```
and at the end of the file 
https://github.com/gmberton/deep-visual-geo-localization-benchmark/blob/main/eval.py#L109
these lines of code
```
import os
import shutil
import numpy as np

OUTPUT_FOLDER = "predictions"

# Load the `predictions`, which is a numpy array of shape `num_queries x 20`
# because for each query there are the indexes of the first 20 predictions
predictions = np.load("predictions.npy")
# Keep only the first 3 predictions of the first 100 queries, to avoid saving too many images
predictions = predictions[:100, :3]  # Comment this line to save predictions for all queries

preds_per_query_txt = ""

if os.path.exists(OUTPUT_FOLDER):
    shutil.rmtree(OUTPUT_FOLDER)

os.makedirs(OUTPUT_FOLDER, exist_ok=True)
# For every query take its predictions
for num_query, query_preds in enumerate(predictions):
    query_path = test_ds.queries_paths[num_query]
    # Save the query to `predictions/query_XXXXX.jpg`
    shutil.copy(query_path, os.path.join(OUTPUT_FOLDER, f"query_{num_query:05d}.jpg"))
    preds_per_query_txt += query_path + ","
    # Save each predictions to disk
    for num_pred, pred in enumerate(query_preds):
        pred_path = test_ds.database_paths[pred]
        shutil.copy(pred_path, os.path.join(OUTPUT_FOLDER, f"query_{num_query:05d}__pred_{num_pred:02d}.jpg"))
        preds_per_query_txt += pred_path + ","
    preds_per_query_txt += "\n"

with open("predictions.csv", "w") as file:
    file.write(preds_per_query_txt)
```

Then after running the script `eval.py` you will have queries and predictions saved in the folder `predictions` which should be easy to inspect, as well as the queries and predictions' paths saved in `predictions.csv`

**Comment by MAX-OTW** [comment]
Hello, @gmberton ,thank you much for your reply!
In addition,If I want to evaluate the performance of algorithms in the Benchmark on Mapillary (Challenge/test) dataset, how should I do it? Have you tried it? If so, can you provide specific implementation steps or some advice？

I am always looking forward to your kind response.
Best regards.

**Comment by wincj** [comment]
May I ask if I need to create a new folder named: predictions  ， Is that all I need to do？
