### ISSUE TITLE
WEBSITE COULD NOT BE REACHED

### ISSUE THREAD

**Issue by Vincentqyw** [gmberton/deep-visual-geo-localization-benchmark#8]
Hi, the [website](https://deep-vg-bench.herokuapp.com/) posted in README cannot be reached.

![Snipaste_2023-01-06_17-20-31](https://user-images.githubusercontent.com/18531182/210970710-052672c0-e2ab-46fe-aaea-bf30cb140593.png)

**Comment by gmberton** [comment]
Thank you for notifying us. The free plan from heroku has been removed, and so the website is now offline.
We are currently investigating other hosting plans.
Anyway, on the website there were a subset of the results from the paper, so you can find everything on the paper (and supplementary).

**Comment by Vincentqyw** [comment]
Got it!
