### ISSUE TITLE
Modelzoo

### ISSUE THREAD

**Issue by aleshem** [gmberton/deep-visual-geo-localization-benchmark#9]
Great paper!
Where can I find the trained models? 
Thanks

**Comment by gmberton** [comment]
Thanks! You can find them in the README, you can expand the sections by clicking on the little black triangle [link](https://github.com/gmberton/deep-visual-geo-localization-benchmark#model-zoo)
![screen](https://user-images.githubusercontent.com/49533159/213927207-3d95bac7-9992-45a9-aac1-b3e6a804cc77.png)
